### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by GXYM** [HaohuaLv/LoRA-Slider#1]
Thank you for your very meaningful project. I have some questions to ask. How many pieces of data are needed to train an age slider model What size is generally suitable for setting the Lora Rank.

**Comment by HaohuaLv** [comment]
This is a method training lora slider without image data, and it is reference and improved on https://github.com/p1atdev/LECO. 
In my case such as age slider, weight slider, rank ≥ 4 for SDv1 and rank ≥ 32 for SDXL are suitable.

**Comment by GXYM** [comment]
> This is a method training lora slider without image data, and it is reference and improved on https://github.com/p1atdev/LECO. In my case such as age slider, weight slider, rank ≥ 4 for SDv1 and rank ≥ 32 for SDXL are suitable.

Thank you. How many pieces of training data are needed to train a satisfactory age slider

**Comment by HaohuaLv** [comment]
> > This is a method training lora slider without image data, and it is reference and improved on https://github.com/p1atdev/LECO. In my case such as age slider, weight slider, rank ≥ 4 for SDv1 and rank ≥ 32 for SDXL are suitable.
> 
> Thank you. How many pieces of training data are needed to train a satisfactory age slider

No image data is required, just prompt. You can refer to Lora-Slider/config/age_slider.json
